media: public
content:
  - name: blogs
    label: Blogs
    type: collection
    path: src/content/blog
    fields:
      - name: title
        type: string
      - name: description
        type: rich-text
      - name: pubDate
        type: date