media:
  input: public
  output: /

content:
  - name: blogs
    label: Blogs
    filename: "{primary}.md"
    path: src/content/blog
    type: collection
    view:
      fields: [ title, draft, date ]
    fields:
      - name: title
        type: string
        
      - name: description
        type: text
        options:
          maxlength: 280
          
      - name: body
        label: Body
        type: rich-text
        
      - name: pubDate
        type: date